Public Class Form1
    Private Sub CONDUCTORESToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles CONDUCTORESToolStripMenuItem.Click
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        RegistrarConductores1.Show()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        If (Login.user.Text = "conductor") Then
            REGISTROToolStripMenuItem.Enabled = False
            ACTUALIZARToolStripMenuItem.Enabled = False
            ELIMINARToolStripMenuItem.Enabled = False
        End If
        RegistarAutos1.Hide()
        RegistrarConductores1.Show()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
        ABRIRCONEXION()
        CN.Close()
    End Sub

    Private Sub AUTOSToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles AUTOSToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        RegistarAutos1.Show()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub TenenciaToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles TenenciaToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        RegistrarTenencia1.Show()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub AccidentesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles AccidentesToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarMultas1.Hide()
        RegistrarTenencia1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        RegistrarAccidentes1.Show()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub MultaToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles MultaToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        EliminarConductores1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        RegistrarMultas1.Show()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub ConductoresToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles ConductoresToolStripMenuItem3.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Show()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub AutosToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles AutosToolStripMenuItem3.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Show()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub TenenciaToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles TenenciaToolStripMenuItem3.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Show()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub AccidentesToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles AccidentesToolStripMenuItem3.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Show()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub MultasToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles MultasToolStripMenuItem2.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Show()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub ConductoresToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles ConductoresToolStripMenuItem2.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Show()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub AutosToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles AutosToolStripMenuItem2.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Show()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub TenenciaToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles TenenciaToolStripMenuItem2.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Show()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub AccidentesToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles AccidentesToolStripMenuItem2.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Show()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub TenenciaToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles TenenciaToolStripMenuItem1.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Show()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub TodosLosAccidentesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles TodosLosAccidentesToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Show()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub ListadoDeMultasToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ListadoDeMultasToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Show()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub LugarDeAccidentesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles LugarDeAccidentesToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Show()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub LugarDeMultasToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles LugarDeMultasToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Show()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub EnAccidentesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles EnAccidentesToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Show()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub EnMultasToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles EnMultasToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Show()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub CerrarSesionToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles CerrarSesionToolStripMenuItem.Click
        Me.Close()
        Login.Show()
    End Sub

    Private Sub PorNumeroDeRefToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles PorNumeroDeRefToolStripMenuItem.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Show()
        ActMultas1.Hide()
    End Sub

    Private Sub PorNumeroDeRefToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles PorNumeroDeRefToolStripMenuItem1.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Show()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Hide()
    End Sub

    Private Sub MultasToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles MultasToolStripMenuItem1.Click
        RegistrarConductores1.Hide()
        RegistarAutos1.Hide()
        RegistrarTenencia1.Hide()
        RegistrarAccidentes1.Hide()
        RegistrarMultas1.Hide()
        EliminarAutos1.Hide()
        EliminarTenencia1.Hide()
        EliminarAccidentes1.Hide()
        EliminarMultas1.Hide()
        EliminarConductores1.Hide()
        ActConductores1.Hide()
        ActAutos1.Hide()
        ActTenencia1.Hide()
        ActAccidentes1.Hide()
        ConsultaTenencia1.Hide()
        ConsultaAccidente1.Hide()
        ConsultaMulta1.Hide()
        ConsultaAccidenteLugar1.Hide()
        ConsultaMultaLugar1.Hide()
        InvolucradosAccidentes1.Hide()
        InvolucradosMultas1.Hide()
        ConsultaMultaRef1.Hide()
        ConsultaAccidenteRef1.Hide()
        ActMultas1.Show()
    End Sub
End Class
