Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles Me.Load
        MenuStrip1.BackColor = Color.DimGray
        MenuStrip1.ForeColor = Color.White
        MenuStrip2.BackColor = Color.DimGray
        MenuStrip2.ForeColor = Color.White

        'For Each Items In MenuStrip1.Items

        'Next

        ABRIRCONEXION()
        If (Login.user.Text = "user") Then
            MenuStrip1.Visible = False
            MenuStrip2.Visible = True
        End If
        If (Login.user.Text = "admin") Then
            MenuStrip1.Visible = True
            MenuStrip2.Visible = False
        End If
    End Sub

    Private Sub ViajerosToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles ViajerosToolStripMenuItem1.Click
        InsertarViajeros1.Show()

        InsertarLugares1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub LugaresToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles LugaresToolStripMenuItem1.Click
        InsertarLugares1.Show()

        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub


    Private Sub AerolineasToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles AerolineasToolStripMenuItem1.Click
        InsertarAerolineas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub RutasToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles RutasToolStripMenuItem1.Click
        InsertarRutas1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub HotelesToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles HotelesToolStripMenuItem1.Click
        InsertarHoteles1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ToursToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles ToursToolStripMenuItem1.Click
        InsertarTours1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajesToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles ViajesToolStripMenuItem1.Click
        InsertarViajes1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajerosToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles ViajerosToolStripMenuItem3.Click
        EliminarViajeros1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub LugaresToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles LugaresToolStripMenuItem3.Click
        EliminarLugares1.Show()

        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarLugares1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub AerolineasToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles AerolineasToolStripMenuItem3.Click
        EliminarAerolineas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub RutasToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles RutasToolStripMenuItem3.Click
        EliminarRutas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub HotelesToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles HotelesToolStripMenuItem3.Click
        EliminarHoteles1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ToursToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles ToursToolStripMenuItem3.Click
        EliminarTours1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajesToolStripMenuItem3_Click(sender As Object, e As EventArgs) Handles ViajesToolStripMenuItem3.Click
        EliminarViajes1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub CerrarSesiónToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles CerrarSesiónToolStripMenuItem.Click
        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()

        Me.Close()
        Login.Show()
    End Sub

    Private Sub ViajerosToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ViajerosToolStripMenuItem.Click
        ConsultarViajeros1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub LugaresToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles LugaresToolStripMenuItem.Click
        ConsultarLugares1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub AerolineasToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles AerolineasToolStripMenuItem.Click
        ConsultarAerolineas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub RutasToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles RutasToolStripMenuItem.Click
        ConsultarRutas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub HotelesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles HotelesToolStripMenuItem.Click
        ConsultarHoteles1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ToursToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ToursToolStripMenuItem.Click
        ConsultarTours1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ViajesToolStripMenuItem.Click
        ConsultarViajes1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajerosToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles ViajerosToolStripMenuItem2.Click
        ActViajeros1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub LugaresToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles LugaresToolStripMenuItem2.Click
        ActLugares1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub AerolineasToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles AerolineasToolStripMenuItem2.Click
        ActAerolineas1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub RutasToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles RutasToolStripMenuItem2.Click
        ActRutas1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub HotelesToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles HotelesToolStripMenuItem2.Click
        ActHoteles1.Show()

        InsertarLugares1.Hide()
        InsertarAerolineas1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActTours1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ToursToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles ToursToolStripMenuItem2.Click
        ActTours1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarAerolineas1.Hide()
        InsertarRutas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActViajes1.Hide()
    End Sub

    Private Sub ViajesToolStripMenuItem2_Click(sender As Object, e As EventArgs) Handles ViajesToolStripMenuItem2.Click
        ActViajes1.Show()

        InsertarLugares1.Hide()
        InsertarViajeros1.Hide()
        InsertarRutas1.Hide()
        InsertarAerolineas1.Hide()
        InsertarHoteles1.Hide()
        InsertarTours1.Hide()
        InsertarViajes1.Hide()
        EliminarViajeros1.Hide()
        EliminarLugares1.Hide()
        EliminarAerolineas1.Hide()
        EliminarRutas1.Hide()
        EliminarHoteles1.Hide()
        EliminarTours1.Hide()
        EliminarViajes1.Hide()
        ConsultarViajeros1.Hide()
        ConsultarLugares1.Hide()
        ConsultarAerolineas1.Hide()
        ConsultarRutas1.Hide()
        ConsultarHoteles1.Hide()
        ConsultarTours1.Hide()
        ConsultarViajes1.Hide()
        ActViajeros1.Hide()
        ActLugares1.Hide()
        ActAerolineas1.Hide()
        ActRutas1.Hide()
        ActHoteles1.Hide()
        ActTours1.Hide()
    End Sub

    Private Sub CerrarSesionToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles CerrarSesionToolStripMenuItem.Click
        Me.Close()
        Login.Show()
    End Sub

    Private Sub ComprarToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ComprarToolStripMenuItem.Click
        ComprarBoleto1.Show()
    End Sub
End Class
